### ISSUE TITLE
Linux support, please

### ISSUE THREAD

**Issue by dayfuaim** [kingToolbox/WindEdit#9]
Please, make Linux supported.
There's already written in "Releases":

> **Linux**
Please use the following command to run the WindEdit after downloading.
>
> tar -xzvf WindEdit_1.0.0_Prerelease_1_Linux_Portable.tar.gz && cd ./WindEdit_1.0.0 && chmod +x ./WindEdit && ./WindEdit
>

But no Linux release in Assets.

Also in #3 it's written: 
> WindEdit is building with Qt, so Linux and Macos will be supported later, I think may be in Q2 2020.

So, it's Q3 2021 here. macOS is here, but what is for Linux? :\

**Comment by kingToolbox** [comment]
I am really very sorry, I have just released the Linux version [WindEdit_1.0.0_Prerelease_1_Linux_Portable](https://github.com/kingToolbox/WindEdit/releases/tag/1.0-prerelease), welcome to download and use.

The problem with WindEdit now is that it only supports a few languages. I am writing more language configurations. I believe there will be a text editor that can be used daily soon. Please keep follow, thank you!

**Comment by dayfuaim** [comment]
@kingToolbox Thank you so much.
Let's use it. :)

**Comment by kingToolbox** [comment]
You can tell me which languages you need, and I will give priority to supporting these languages :smile:
